# Generated by Django 4.2 on 2023-10-16 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsearchhistory',
            name='search_query',
            field=models.CharField(max_length=255, verbose_name='Search Query'),
            preserve_default=False,
        ),
    ]
