# Generated by Django 4.2 on 2023-10-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_module', '0002_documentsearchhistory_search_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsearchhistory',
            name='document',
            field=models.ManyToManyField(related_name='history_search_documents', to='document_module.document', verbose_name='Document'),
        ),
    ]
